# Build configuration
services:
  production:
    image: craftarc/axel:production
    build:
      context: ${PROJECT_ROOT}
      dockerfile: env/production/production.Dockerfile
      args:
        APP_ROOT: ${APP_ROOT}
        CONFIG_PATH: ${CONFIG_PATH}