---
title: Class diagram for the aws::lambda_runtime::invocation_request struct
---
classDiagram
    class invocation_request {
        +std:: string payload
        +std:: string request_id
        +std:: string xray_trace_id
        +std:: string client_context
        +std:: string cognito_identity
        +std:: string function_arn
        +std:: chrono:: time_point<std:: chrono:: system_clock> deadline
        +inline std:: chrono:: milliseconds get_time_remaining() const
    }