---
title: Oauth Flow - DbManager
---
sequenceDiagram
    participant OM as OauthManager
    participant DM as DbManager
    participant AuthDB as Auth DynamoDB
    participant AxelDB as Axel DynamoDB
    alt AuthDB
        OM ->>+ DM: store_session_data(AuthDB, auth_session_token, state_hash)
        DM ->>+ AuthDB: store(auth_session_token, state_hash)
        AuthDB -->>- DM: returns if successful
        DM -->>- OM: returns if successful
    else AxelDB
        OM ->>+ DM: store_session_data(AxelDB, axel_session_token)
        DM ->>+ AxelDB: store(axel_session_token)
        AxelDB -->>- DM: returns if successful
        DM -->>- OM: returns if successful
    end
