---
title: Oauth Flow - Overview
---

sequenceDiagram
    participant Browser as User's Browser
    participant Auth as Auth Server
    participant Lambda as Lambda Function
    participant OM as OAuthManager

    box gray Backend
        participant Lambda
        participant OM
    end

    Browser ->> Lambda: login_user()
    activate Lambda
    Lambda ->> OM: start_oauth()
    activate OM
    note over OM: State: INITIAL
    OM -->> Lambda: authorization_url
    note over OM: State: USER_REDIRECTED
    Lambda -->> Browser: authorization_url
    Browser ->> Auth: Auth user
    activate Auth
    note right of Auth: Authorisation <br> received from user
    Auth -->> Browser: auth_code
    deactivate Auth
    Browser ->> Lambda: receive_auth_response()
    note over Browser, Lambda: auth_code and state attached
    Lambda ->> OM: receive_authorization_code()
    note over OM: State: AUTH_CODE_RECEIVED
    OM ->> Auth: do_exchange()
    activate Auth
    note over OM: State: EXCHANGE_REQUEST_SENT
    Auth -->> OM: access_token, refresh_token
    deactivate Auth
    note over OM: State: TOKENS_RECEIVED
    OM -->> Lambda: session_jwt
    deactivate OM
    note over OM: State: SESSION_ESTABLISHED
    Lambda -->> Browser: session_jwt
