services:
  dev:
    image: craftarc/axel:dev
    build:
      context: ../..
      dockerfile: env/dev/dev.Dockerfile

    ports:
      - "80:80" # Axel app
      - "8080:8080" # Python test server
    volumes:
      - ${PROJECT_ROOT}:${PROJECT_ROOT}
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - config:/root
    environment:
      - PROJECT_ROOT=${PROJECT_ROOT}

volumes:
  config:

