services:
  dev:
    image: craftarc/axel:dev
    build:
      context: ../..
      dockerfile: env/dev/dev.Dockerfile

    ports:
      - "80:80" # Axel app
      - "8080:8080" # Python test server
    volumes:
      - ${APP_ROOT}:${APP_ROOT}
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - config:/root
    environment:
      - APP_ROOT=${APP_ROOT}

volumes:
  config:

