# Build configuration
services:
  dev:
    image: craftarc/axel:dev
    build:
      context: ../..
      dockerfile: env/dev/dev.Dockerfile
    ports:
      - "80:80" # Axel app
    volumes:
      - ${HOST_ROOT}:${APP_ROOT} # Mount project root
    environment: # For inside container
      - APP_ROOT=${APP_ROOT}