services:
  dev:
    image: craftarc/axel:dependencies
    build:
      context: ../..
      dockerfile: env/dev/dependencies.Dockerfile

    ports:
      - "80:80" # Axel app
      - "8080:8080" # Python test server
    volumes:
      - ${MOUNT}:${MOUNT}
