services:
  dev:
    image: craftarc/axel:dependencies
    build:
      context: ../..
      dockerfile: env/dev/dependencies.Dockerfile

    ports:
      - "9000:8080"
    volumes:
      - ${MOUNT}:${MOUNT}
      - ~/.ssh:/root/.ssh
