services:
  dev:
    image: craftarc/axel:dependencies
    build:
      context: .
      dockerfile: dockerfile/dependencies.Dockerfile

    ports:
      - "9000:8080"
    volumes:
      - ~/.aws:/root/.aws # Credentials file
      - ../../:${PWD}
      - ~/.aws-lambda-rie:/aws-lambda # RIE binary
      - ~/.ssh:/root/.ssh
    environment:
      - AWS_LAMBDA_RUNTIME_API=localhost:9000
    command: [ "scripts/dev/start.sh" ]
