services:
  staging:
    image: craftarc/axel:staging
    build:  
      context: ${PROJECT_ROOT}
      dockerfile: env/release.Dockerfile
      args:
        APP_ROOT: ${APP_ROOT}
        CONFIG_PATH: ${CONFIG_PATH}
    ports: 
      - "80:80"
      - "443:443"

    environment:
      - APP_ROOT=${APP_ROOT}

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt # Mount SSL keys

  oauth:
    image: craftarc/axel:oauth
    build:
      context: ${PROJECT_ROOT}
      dockerfile: env/staging/oauth.Dockerfile
      args:
        APP_ROOT: ${APP_ROOT}
        PROJECT_ROOT: ${PROJECT_ROOT}
    ports:
      - "8080:8080"
    environment:
      - APP_ROOT=${APP_ROOT}
    stdin_open: true
    tty: true
