services:
  staging:
    image: craftarc/axel:staging
    build:  
      context: ${PROJECT_ROOT}
      dockerfile: env/staging/staging.Dockerfile
      args:
        APP_ROOT: ${APP_ROOT}
    ports: 
      - "8081:80"
    command: [nginx, '-g', 'daemon off;'] # Start server in foreground so
                                          # the container doesn't stop immediately
    environment:
      - APP_ROOT=${APP_ROOT}
