---
title: Backend
---
classDiagram
    class BankAccount
    <<interface>>
    BankAccount: +String owner
    BankAccount: +Bigdecimal balance
    BankAccount: +deposit(amount)
    BankAccount: +withdrawal(amount)