---
title: High-level overview of Oauth flow
---
sequenceDiagram
    actor User as User
    participant Client as Qt Client
    participant Browser as Browser
    participant Backend as Backend Server
    participant Auth as Auth Server

    User ->>+ Client: Initiate login
    Client ->>+ Browser: Direct to /authorize
    Browser ->>+ Backend: User authenticates
    Backend ->> Backend: Generate PKCE tokens
    Backend ->>+ Auth: Send auth and code challenge
    Auth -->>- Backend: Return authorisation code
    Backend -->> Browser: Redirect to local URI with JWT
    Backend ->>+ Auth: Request access token
    Auth -->>- Backend: Return access token


    deactivate Backend






